server:
  port: 7070
  servlet:
    context-path: /messenger
  forward-headers-strategy: framework
  
spring:
  data:
    mongodb: 
      database: gigety
      uri: mongodb://${DEV_GIGETY_USR}:${DEV_GIGETY_PW}@localhost:27017/gigety
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 61613
    username: guest
    password: guest
    
stomp:
  broker:
    relay: /topic
    app:   
      destination:
        prefixes: /msg, /user
    user: 
      destination:
        prefix: /user
        
logging:
  level: 
    com.gigety.ws: debug
    org.springframework.messaging: debug
    
gig:
  message-pageable-size: 5