server:
  port: 7070
  servlet:
    context-path: /messenger
  forward-headers-strategy: framework
  
spring:
  data:
    mongodb: 
      database: gigety
      uri: mongodb://${DEV_GIGETY_USR}:${DEV_GIGETY_PW}@localhost:27017/gigety
      auto-index-creation: true
  activemq:
    broker-url: stomp://localhost:61613
    user: admin
    password: admin
    in-memory: false
     
active-mq-url: stomp://localhost:61613
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
    
logging:
  level: 
    com.gigety.ws: debug
    org.springframework.messaging: debug
    
gig:
  message-pageable-size: 5