version: '3.7'

services:
    gigety-nginx:
        container_name: gigety-nginx
        depends_on:
            - gigety-user-registration
            - gigety-web-api-mysql
            - gigety-reactjs
        ports:
            - '80:80'

    gigety-ur-mysql:
        image: mysql
        container_name: gigety-ur-mysql

    gigety-web-api-mysql:
        image: mysql
        container_name: gigety-web-api-mysql

    gigety-redis:
        image: redis
        container_name: gigety-redis

    gigety-user-registration:
        container_name: gigety-user-registration
        depends_on:
            - gigety-ur-mysql

    gigety-web-api:
        container_name: gigety-web-api
        depends_on:
            - gigety-web-api-mysql
        ports:
            - 8080:8080
            - 8000:8000

    gigety-reactjs:
        container_name: gigety-reactjs
