version: '3.7'

services:
    gigety:
        image: traefik:1.7.3
        command: --web \
            --docker \
            --docker.swarmmode \
            --docker.domain=gigety.com \
            --acme.email=samuelmosessegal@gmail.com
            --acme.httpChallenge.entryPoint=http
            --logLevel=DEBUG
        networks:
            - gigety
        ports:
            - '80:80'
            - '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-nginx]
            placement:
                constraints: [node.role==manager]
    gigety-ur-mysql:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-ur-mysql]

    gigety-web-api-mysql:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-web-api-mysql]

    gigety-redis:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-redis]

    gigety-user-registration:
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - 'APP=gigety-user-registration'
                - 'traefik.enable=true'
                - 'traefik.port=8080'
                - 'traefik.docker.network=gigety'
                - 'traefik.frontend.rule=Host:gigety.com/ur'
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s

    gigety-web-api:
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - 'APP=gigety-web-api'
                - 'traefik.enable=true'
                - 'traefik.port=8080'
                - 'traefik.docker.network=gigety'
                - 'traefik.frontend.rule=Host:gigety.com/api'
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s

    gigety-reactjs:
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - 'APP=gigety-reactjs'
                - 'traefik.enable=true'
                - 'traefik.port=3000'
                - 'traefik.docker.network=gigety'
                - 'traefik.frontend.rule=Host:gigety.com'
