version: '3.7'

services:
    gigety-ur-mysql:
        image: mysql
        container_name: gigety-ur-mysql

    gigety-web-api-mysql:
        image: mysql
        container_name: gigety-web-api-mysql

    gigety-redis:
        image: redis:alpine3.11
        container_name: gigety-redis

    gigety-user-registration:
        container_name: gigety-user-registration
        depends_on:
            - gigety-ur-mysql

    gigety-web-api:
        container_name: gigety-web-api
        depends_on:
            - gigety-web-api-mysql

    gigety-reactjs:
        container_name: gigety-reactjs
