version: '3.7'

services:
    gigety-mysql:
        secrets:
            - DEV_GIGETY_PW
            - DEV_GIGETY_USR
        environment:
            MYSQL_ROOT_PASSWORD_FILE: ${RUN_SECRETS}/DEV_GIGETY_PW
            MYSQL_USER_FILE: ${RUN_SECRETS}/DEV_GIGETY_USR
            MYSQL_PASSWORD_FILE: ${RUN_SECRETS}/DEV_GIGETY_PW
            MYSQL_ROOT_HOST: '%'
        volumes:
            - gigety-mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - gigety-mysql

    gigety-web-api-mongo:
        secrets:
            - GIGETY_MONGO_ROOT_USR_NAME
            - GIGETY_MONGO_ROOT_PW
            - GIGETY_MONGO_USR_NAME
            - GIGETY_MONGO_USR_PW
            - MONGO_INITDB_DATABASE
        environment:
            MONGO_INITDB_ROOT_USERNAME_FILE: ${RUN_SECRETS}/GIGETY_MONGO_ROOT_USR_NAME
            MONGO_INITDB_ROOT_PASSWORD_FILE: ${RUN_SECRETS}/GIGETY_MONGO_ROOT_PW
            GIGETY_MONGO_USR_NAME_FILE: ${RUN_SECRETS}/GIGETY_MONGO_USR_NAME
            GIGETY_MONGO_USR_PW_FILE: ${RUN_SECRETS}/GIGETY_MONGO_USR_PW
            MONGO_INITDB_DATABASE_FILE: ${RUN_SECRETS}/MONGO_INITDB_DATABASE
        volumes:
            - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        networks:
            - gigety-mongo
        hostname: gigety-web-api-mongo

    gigety-redis:
        secrets:
            - DEV_GIGETY_PW
        command: redis-server --requirepass ${DEV_GIGETY_PW}
        networks:
            - gigety

    gigety-user-registration:
        image: samuelsegal/gigety-user-registration
        secrets:
            - DEV_GIGETY_PW
            - DEV_GIGETY_USR
            - SMS_GMAIL_PW
            - SMS_GMAIL_NAME
        environment:
            DEV_GIGETY_USR_FILE: ${RUN_SECRETS}/DEV_GIGETY_USR
            DEV_GIGETY_PW_FILE: ${RUN_SECRETS}/DEV_GIGETY_PW
            SMS_GMAIL_PW_FILE: ${RUN_SECRETS}/SMS_GMAIL_PW
            SMS_GMAIL_NAME_FILE: ${RUN_SECRETS}/SMS_GMAIL_NAME
        restart: always
        networks:
            - gigety-mysql
            - gigety

    gigety-web-api:
        image: samuelsegal/gigety-web-api
        secrets:
            - DEV_GIGETY_PW
            - DEV_GIGETY_USR
            - MONGO_INITDB_DATABASE
            - GIGETY_MONGO_USR_NAME
            - GIGETY_MONGO_USR_PW
            - GIGETY_GOOGLE_CLIENT_ID
            - GIGETY_GOOGLE_CLIENT_SECRET
            - GIGETY_FACEBOOK_APP_ID
            - GIGETY_FACEBOOK_APP_SECRET
        environment:
            DEV_GIGETY_USR_FILE: ${RUN_SECRETS}/DEV_GIGETY_USR
            DEV_GIGETY_PW_FILE: ${RUN_SECRETS}/DEV_GIGETY_PW
            GIGETY_GOOGLE_CLIENT_ID_FILE: ${RUN_SECRETS}/GIGETY_GOOGLE_CLIENT_ID
            GIGETY_GOOGLE_CLIENT_SECRET_FILE: ${RUN_SECRETS}/GIGETY_GOOGLE_CLIENT_SECRET
            GIGETY_FACEBOOK_APP_ID_FILE: ${RUN_SECRETS}/GIGETY_FACEBOOK_APP_ID
            GIGETY_FACEBOOK_APP_SECRET_FILE: ${RUN_SECRETS}/GIGETY_FACEBOOK_APP_SECRET
            GIGETY_MONGO_USR_NAME_FILE: ${RUN_SECRETS}/GIGETY_MONGO_USR_NAME
            GIGETY_MONGO_USR_PW_FILE: ${RUN_SECRETS}/GIGETY_MONGO_USR_PW
            MONGO_INITDB_DATABASE_FILE: ${RUN_SECRETS}/MONGO_INITDB_DATABASE
        restart: always
        networks:
            - gigety
            - gigety-mysql
            - gigety-mongo

    gigety-reactjs:
        stdin_open: true
        image: samuelsegal/gigety-reactjs
        environment:
            REACT_APP_GIGETY_URL: 'https://gigety.com'
            #THIS IS TEMPORARY REACT_APP_GIGETY_GOOGLE_GEOCODE_API_KEY needs somehow to be a secret that works in react
            REACT_APP_GIGETY_GOOGLE_GEOCODE_API_KEY: '${REACT_APP_GIGETY_GOOGLE_GEOCODE_API_KEY}'
        networks:
            - gigety
networks:
    gigety:
        #driver: overlay
        #attachable: true
        external: true
        #NOTE: after upgrading docker-compose this is throwing an error.
        # temporary fix is to comment external true out than re adding it when going to deploy
        # However this needs to be revisited for perma fix
    gigety-mysql:
        driver: overlay
        attachable: true
    gigety-mongo:
        driver: overlay
        attachable: true
        #ipam:
        #    driver: default
        #    config:
        #        - subnet: '192.168.99.0/24'

secrets:
    DEV_GIGETY_PW:
        file: ./secrets/DEV_GIGETY_PW.txt
    DEV_GIGETY_USR:
        file: ./secrets/DEV_GIGETY_USR.txt
    GIGETY_GOOGLE_CLIENT_ID:
        file: ./secrets/GIGETY_GOOGLE_CLIENT_ID.txt
    GIGETY_GOOGLE_CLIENT_SECRET:
        file: ./secrets/GIGETY_GOOGLE_CLIENT_SECRET.txt
    GIGETY_FACEBOOK_APP_ID:
        file: ./secrets/GIGETY_FACEBOOK_APP_ID.txt
    GIGETY_FACEBOOK_APP_SECRET:
        file: ./secrets/GIGETY_FACEBOOK_APP_SECRET.txt
    SMS_GMAIL_PW:
        file: ./secrets/SMS_GMAIL_PW.txt
    SMS_GMAIL_NAME:
        file: ./secrets/SMS_GMAIL_NAME.txt
    GIGETY_MONGO_ROOT_PW:
        file: ./secrets/GIGETY_MONGO_ROOT_PW.txt
    GIGETY_MONGO_ROOT_USR_NAME:
        file: ./secrets/GIGETY_MONGO_ROOT_USR_NAME.txt
    GIGETY_MONGO_USR_PW:
        file: ./secrets/GIGETY_MONGO_USR_PW.txt
    GIGETY_MONGO_USR_NAME:
        file: ./secrets/GIGETY_MONGO_USR_NAME.txt
    MONGO_INITDB_DATABASE:
        file: ./secrets/MONGO_INITDB_DATABASE.txt

volumes:
    gigety-mysql:
    gigety-web-api:
    gigety-user-registration:
