version: '3.7'

services:
    gigety-nginx:
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        volumes:
            - ./gigety-nginx/certbot/conf:/etc/letsencrypt
            - ./gigety-nginx/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./gigety-nginx/certbot/conf:/etc/letsencrypt
            - ./gigety-nginx/certbot/www:/var/www/certbot
