version: '3.7'

services:
    gigety-nginx:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-nginx]

    gigety-ur-mysql:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-ur-mysql]

    gigety-web-api-mysql:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-web-api-mysql]

    gigety-redis:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-redis]

    gigety-user-registration:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-user-registration]
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s

    gigety-web-api:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-web-api]
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s

    gigety-reactjs:
        deploy:
            mode: replicated
            replicas: 1
            labels: [APP=gigety-reactjs]
