version: '3.7'
services:
    traefik:
        image: traefik:latest
        ports:
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
            - target: 8080
              published: 8080
              mode: host
        command: >
            --api
            --entrypoints='Name:http Address::80'
            --entrypoints='Name:https Address::443 TLS'
            --defaultentrypoints=http,https
            --acme
            --acme.storage=/etc/traefik/acme.json
            --acme.entryPoint=https
            --acme.httpChallenge.entryPoint=http
            --acme.onHostRule=true
            --acme.onDemand=false
            --acme.email=${EMAIL:-root@localhost}
            --docker
            --docker.swarmMode
            --docker.domain=${DOMAIN:-localhost}
            --docker.watch

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /mnt/traefik/acme.json:/etc/traefik/acme/acme.json
        networks:
            - gigety
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
configs:
    traefik_htpasswd:
        file: ./htpasswd

networks:
    gigety:
        driver: overlay
        external: true
