version: '3.7'

services:
    localhost.com:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./gigety-nginx
        networks:
            - gigety
        ports:
            - '80:80'
        depends_on:
            - gigety-user-registration
            - gigety-web-api
    gigety-mysql:
        environment:
            MYSQL_ROOT_PASSWORD: ${DEV_GIGETY_PW}
            MYSQL_USER: ${DEV_GIGETY_USR}
            MYSQL_PASSWORD: ${DEV_GIGETY_PW}
        volumes:
            - ${GIGETY_UR_MYSQL}:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - gigety-mysql

    gigety-web-api-mongo:
        hostname: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ${GIGETY_API_MONGO}:/data/db
        networks:
            - gigety-web-api-mongo
        command: mongod --logpath=/dev/null # --quiet

    gigety-redis:
        command: redis-server --requirepass ${DEV_GIGETY_PW}
        networks:
            - gigety

    gigety-user-registration:
        build:
            context: ./gigety-user-registration
            dockerfile: Dockerfile
        #TODO: Remote debugging not working for user-registration, probably something a config in the project, revisit
        #command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001 -jar build/libs/gigety-user-registration-0.0.1-SNAPSHOT.jar
        volumes:
            - gigety-user-registration:/data/gigety-user-registration
        environment:
            DEV_GIGETY_USR: ${DEV_GIGETY_USR}
            DEV_GIGETY_PW: ${DEV_GIGETY_PW}
            SMS_GMAIL_PW: ${SMS_GMAIL_PW}
            SMS_GMAIL_NAME: ${SMS_GMAIL_NAME}
        restart: always
        networks:
            - gigety-mysql
            - gigety

    gigety-web-api:
        build:
            context: ./gigety-web-api
            dockerfile: Dockerfile.dev
        # ENABLING REMOTE DEBUG FOR gigety-web-api
        #command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar build/libs/gigety-web-api-0.0.1-SNAPSHOT.jar
        volumes:
            - ./gigety-web-api:/data/gigety-web-api
            #- gigety-web-api:/data/gigety-web-api
        ports:
            - 8000:8000
            - 8080:8080
        environment:
            DEV_GIGETY_USR: ${DEV_GIGETY_USR}
            DEV_GIGETY_PW: ${DEV_GIGETY_PW}
            GIGETY_GOOGLE_CLIENT_ID: ${GIGETY_GOOGLE_CLIENT_ID}
            GIGETY_GOOGLE_CLIENT_SECRET: ${GIGETY_GOOGLE_CLIENT_SECRET}
            GIGETY_FACEBOOK_APP_ID: ${GIGETY_FACEBOOK_APP_ID}
            GIGETY_FACEBOOK_APP_SECRET: ${GIGETY_FACEBOOK_APP_SECRET}
        restart: always
        networks:
            - gigety
            - gigety-mysql

    gigety-reactjs:
        stdin_open: true
        environment:
            REACT_APP_GIGETY_URL: ${REACT_APP_GIGETY_URL}
        build:
            context: ./gigety-reactjs/react-gigety
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./gigety-reactjs/react-gigety:/app
        networks:
            - gigety
networks:
    gigety:
        driver: bridge
    gigety-mysql:
        driver: bridge
    gigety-web-api-mongo:
        driver: bridge

volumes:
    gigety-web-api:
    gigety-user-registration:
