spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gigety_users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #naming:
      #  implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #  physical-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google: 
            client-id:
              ${SPRING_OAUTH_GOOGLE_CLIENT_ID}
            client-secret:
              ${SPRING_OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri:
              "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id:
              ${SPRING_OAUTH_FACEBOOK_APP_ID}
            client-secret:
              ${SPRING_OAUTH_FACEBOOK_APP_SECRET}
            redirect-uri:
              "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook: 
            authorization-uri: 
              https://www.facebook.com/v3.0/dialog/oauth
            token-uri:
              https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri:
              https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
gig:
  auth:
    token-secret: gigety-token-secret
    token-expiration-msec: 864000000
  oauth2:
    authorized-redirect-uris:
      # After authenticating with OAuth2 Provider
      # We generate an auth token for the user. 
      # redirect to the uri mentioned by front end in /oath2/authorize
      # we do not use cookies as they will not work for mobile
      - http://localhost:3000/oauth2/redirect
      - androidapp://oauth2/redirect
      - iosapp://oauth2/redirect
  endpoints:
    web:
      cors:
        allowed-origins: 
          - http://localhost:3000
          - http://gigety.com
        allowed-methods: 
          - "*"
logging:
  level:
    com.gigety.web.api: debug
              