export const SET_CURRENT_USR = 'SET_CURRENT_USR';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_CURRENT_USR = 'GET_CURRENT_USR';
export const GET_CURRENT_ADDRESS = 'GET_CURRENT_ADDRESS';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_PROFILE_TITLE = 'SET_PROFILE_TITLE';
export const SET_PROFILE_CREATED_SUCCESS = 'SET_PROFILE_CREATED_SUCCESS';
export const SET_PROFILE_CREATED_ERROR = 'SET_PROFILE_CREATED_ERROR';
export const SET_PROFILE_CREATED_WAITING = 'SET_PROFILE_CREATED_WAITING';
export const SET_PROFILE_ADDRESS = 'SET_PROFILE_ADDRESS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const SEARCH_ALL_PROFILES = 'SEARCH_ALL_PROFILES';
export const FOUND_PROFILE_SEARCH_RESULTS = 'FOUND_PROFILE_SEARCH_RESULTS';
export const REMOVE_PROFILE_SUCCESS = 'REMOVE_PROFILE_SUCCESS';

export const WAITING_FOR_RESPONSE = 'WAITING_FOR_RESPONSE';
export const GET_CURRENT_USR_ACCOUNT = 'GET_CURRENT_USR_ACCOUNT';

export const SEARCH_ALL_GIGS = 'SEARCH_ALL_GIGS';
export const FOUND_GIG_SEARCH_RESULTS = 'FOUND_GIG_SEARCH_RESULTS';
export const SET_GIG_CREATED_SUCCESS = 'SET_GIG_CREATED_SUCCESS';
export const SET_GIG_CREATED_ERROR = 'SET_GIG_CREATED_ERROR';
export const SET_GIG_CREATED_WAITING = 'SET_GIG_CREATED_WAITING';
export const GET_GIG = 'GET_GIG';

export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
