# Allow Thymeleaf to hot reload
spring:
  thymeleaf:
    cache: false

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${SMS_GMAIL_NAME} 
    password: ${SMS_GMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
    
  banner:
    image:
      height: 2
      
  jpa:
    hibernate:
      ddl-auto: create-drop
  
  datasource:
    # Set initialization-mode: always for schema.sql to execute on startup for databases other than 
    # H2,DERBY,HSQL. These are only enabled databases by default for data initializing
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/gigety_um?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    # url: jdbc:mysql://samo-mysql:3306/gigety_um?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: 
    # driver-class-name: com.mysql.jdbc.Driver 
    
server:
  tomcat:
    accesslog:
      enabled: true
    basedir:
      target/tomcat
      
  port: 8084

logging:
  level:
    com.gigety.ur: debug
    # org.springframework.security: debug
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
 
gigety: 
  root-url: http://localhost:8083
  email:
    support: samuelmosessegal@gmail.com